### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by ryandw11** [kakaragame/Engine#54]
## AtlasMesh Bug
```
[←[0;31mERROR←[m] May 03, 05:30 PM GameEngine: Exception Thrown inside org.kakara.client.scenes.maingamescene.MainGameScene
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.base/java.util.ArrayList$Itr.next(Unknown Source)
        at org.kakara.engine.gameitems.mesh.AtlasMesh.renderList(AtlasMesh.java:206)
        at org.kakara.engine.render.preset.pipeline.StandardPipeline.renderNonInstancedMeshes(StandardPipeline.java:97)
        at org.kakara.engine.render.preset.pipeline.StandardPipeline.render(StandardPipeline.java:69)
        at org.kakara.engine.render.Renderer.render(Renderer.java:92)
        at org.kakara.engine.scene.AbstractGameScene.render(AbstractGameScene.java:37)
        at org.kakara.engine.scene.SceneManager.renderCurrentScene(SceneManager.java:53)
        at org.kakara.engine.GameEngine.render(GameEngine.java:181)
        at org.kakara.engine.GameEngine.gameLoop(GameEngine.java:129)
        at org.kakara.engine.GameEngine.run(GameEngine.java:84)
        at org.kakara.client.GameLoader.load(GameLoader.java:17)
        at org.kakara.client.Main.main(Main.java:49)
```

## Color Text Glitch
```
[←[0;31mERROR←[m] May 03, 05:39 PM GameEngine: Exception Thrown inside org.kakara.client.scenes.maingamescene.MainGameScene
java.lang.StringIndexOutOfBoundsException: begin 3, end 5, length 4
        at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
        at java.base/java.lang.String.substring(Unknown Source)
        at org.kakara.engine.ui.components.text.BoundedColoredText.hex2Rgb(BoundedColoredText.java:255)
        at org.kakara.engine.ui.components.text.BoundedColoredText.isChatCode(BoundedColoredText.java:244)
        at org.kakara.engine.ui.components.text.BoundedColoredText.splitColors(BoundedColoredText.java:228)
        at org.kakara.engine.ui.components.text.BoundedColoredText.calculateLineNumbers(BoundedColoredText.java:110)
        at org.kakara.client.scenes.uicomponenets.ChatComponent.render(ChatComponent.java:272)
        at org.kakara.engine.ui.canvases.ComponentCanvas.render(ComponentCanvas.java:78)
        at org.kakara.engine.ui.UserInterface.render(UserInterface.java:82)
        at org.kakara.engine.scene.AbstractGameScene.render(AbstractGameScene.java:40)
        at org.kakara.engine.scene.SceneManager.renderCurrentScene(SceneManager.java:53)
        at org.kakara.engine.GameEngine.render(GameEngine.java:181)
        at org.kakara.engine.GameEngine.gameLoop(GameEngine.java:129)
        at org.kakara.engine.GameEngine.run(GameEngine.java:84)
        at org.kakara.client.GameLoader.load(GameLoader.java:17)
        at org.kakara.client.Main.main(Main.java:49)
[←[0;37mINFO←[m] May 03, 05:39 PM KakaraGame: Terminat
```

**Comment by ryandw11** [comment]
This bug report will stay open for a while to ensure the issues are 100% fixed.
